# Generated by Django 5.1.4 on 2025-04-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmemorial', '0002_petmemorial_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmemorial',
            name='about_pet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petmemorial',
            name='breed',
            field=models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('guinea_pig', 'Guinea Pig'), ('ferret', 'Ferret'), ('bird', 'Bird'), ('parrot', 'Parrot'), ('turtle', 'Turtle'), ('lizard', 'Lizard'), ('snake', 'Snake'), ('fish', 'Fish'), ('horse', 'Horse'), ('goat', 'Goat'), ('pig', 'Pig'), ('chicken', 'Chicken'), ('duck', 'Duck'), ('frog', 'Frog'), ('hedgehog', 'Hedgehog'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='petmemorial',
            name='dominant_traits',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='petmemorial',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('guinea_pig', 'Guinea Pig'), ('ferret', 'Ferret'), ('bird', 'Bird'), ('parrot', 'Parrot'), ('turtle', 'Turtle'), ('lizard', 'Lizard'), ('snake', 'Snake'), ('fish', 'Fish'), ('horse', 'Horse'), ('goat', 'Goat'), ('pig', 'Pig'), ('chicken', 'Chicken'), ('duck', 'Duck'), ('frog', 'Frog'), ('hedgehog', 'Hedgehog'), ('other', 'Other')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
