# Generated by Django 5.1.4 on 2025-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmemorial', '0003_petmemorial_about_pet_petmemorial_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmemorial',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
