# Generated by Django 5.1.4 on 2025-04-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmemorial', '0004_alter_petmemorial_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmemorial',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
