# Generated by Django 5.1.4 on 2025-04-20 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmemorial', '0005_petmemorial_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetMemorialGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('pet_memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='petmemorial.petmemorial')),
            ],
        ),
    ]
