# Generated by Django 5.1.4 on 2025-04-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmemorial', '0006_petmemorialgalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet_memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='petmemorial.petmemorial')),
            ],
        ),
    ]
