# Generated by Django 5.1.4 on 2025-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmemorial', '0007_candlemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmemorial',
            name='owner_display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
