# Generated by Django 5.1.4 on 2025-04-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmemorial', '0008_petmemorial_owner_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmemorial',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
