# Generated by Django 5.1.4 on 2025-04-23 06:24

import petmemorial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmemorial', '0009_alter_petmemorial_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmemorial',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='petmemorial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=petmemorial.models.pet_memorial_profile_photo_path),
        ),
        migrations.AlterField(
            model_name='petmemorialgalleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=petmemorial.models.gallery_image_upload_path),
        ),
    ]
